"""cria tabela clinic_config

Revision ID: 3821d8101e7c
Revises: ddbe10b4dc0f
Create Date: 2025-05-03 18:55:29.048535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3821d8101e7c'
down_revision: Union[str, None] = 'ddbe10b4dc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('nome_clinica', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id')
    )
    op.drop_table('especialidades')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clinica_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chave', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('profissional', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resposta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('palavras_chave', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], name='especialidades_clinica_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='especialidades_pkey')
    )
    op.drop_table('clinic_config')
    # ### end Alembic commands ###
