"""Atualiza estrutura de leads com clinic_id como String

Revision ID: ddbe10b4dc0f
Revises: f39d1180893a
Create Date: 2025-05-01 03:09:39.756479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddbe10b4dc0f'
down_revision: Union[str, None] = 'f39d1180893a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
