"""Tabela limpa com clinica_id string

Revision ID: f39d1180893a
Revises: 
Create Date: 2025-05-01 01:32:19.547855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f39d1180893a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_conversa')
    op.alter_column('perguntas_frequentes', 'clinica_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('perguntas_frequentes', 'pergunta',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('perguntas_frequentes', 'resposta',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('perguntas_frequentes', 'resposta',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('perguntas_frequentes', 'pergunta',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('perguntas_frequentes', 'clinica_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
    op.create_table('historico_conversa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telefone_usuario', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('mensagem_usuario', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resposta_clara', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='historico_conversa_pkey')
    )
    # ### end Alembic commands ###
